In [1]:
import pandas as pd

# Load the CSV into a DataFrame
df = pd.read_csv('heart_disease.csv')

df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [2]:
df.shape

(10000, 21)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [4]:
import numpy as np
df.iloc[:, -1]
classes = pd.Series(np.where(df.iloc[:, -1].values == 'Yes', 1, 0),
          df.index)

print(classes.mean())

0.2

In [5]:
df.describe()

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
count,9971.000000,9981.000000,9970.000000,9978.000000,9975.000000,9974.000000,9978.000000,9974.000000,9980.000000
mean,49.296259,149.757740,225.425577,29.077269,6.991329,250.734409,120.142213,7.472201,12.456271
std,18.193970,17.572969,43.575809,6.307098,1.753195,87.067226,23.584011,4.340248,4.323426
min,18.000000,120.000000,150.000000,18.002837,4.000605,100.000000,80.000000,0.003647,5.000236
25%,34.000000,134.000000,187.000000,23.658075,5.449866,176.000000,99.000000,3.674126,8.723334
50%,49.000000,150.000000,226.000000,29.079492,7.003252,250.000000,120.000000,7.472164,12.409395
75%,65.000000,165.000000,263.000000,34.520015,8.531577,326.000000,141.000000,11.255592,16.140564
max,80.000000,180.000000,300.000000,39.996954,9.999952,400.000000,160.000000,14.997087,19.999037

In [6]:
df.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [7]:
# Get lists of numeric and categorical columns
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

# Let's print them to double-check
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours', 'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level', 'Homocysteine Level']
Categorical Columns: ['Gender', 'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level', 'Sugar Consumption', 'Heart Disease Status']

In [8]:
# Fill missing numerical columns with their median value
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        median_value = df[col].median()
        df[col].fillna(median_value, inplace=True)

/var/folders/bz/fh28p9s15rz0cpb5v9315b2c0000gn/T/ipykernel_2577/3897643297.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_value, inplace=True)

In [9]:
# Fill missing categorical columns with their mode (most frequent value)
for col in categorical_cols:
    if col != 'Alcohol Consumption':  # Skip Alcohol Consumption for now
        if df[col].isnull().sum() > 0:
            mode_value = df[col].mode()[0]
            df[col].fillna(mode_value, inplace=True)

/var/folders/bz/fh28p9s15rz0cpb5v9315b2c0000gn/T/ipykernel_2577/476271990.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)

In [10]:
df.isna().sum()

Age                        0
Gender                     0
Blood Pressure             0
Cholesterol Level          0
Exercise Habits            0
Smoking                    0
Family Heart Disease       0
Diabetes                   0
BMI                        0
High Blood Pressure        0
Low HDL Cholesterol        0
High LDL Cholesterol       0
Alcohol Consumption     2586
Stress Level               0
Sleep Hours                0
Sugar Consumption          0
Triglyceride Level         0
Fasting Blood Sugar        0
CRP Level                  0
Homocysteine Level         0
Heart Disease Status       0
dtype: int64

In [11]:
df.isnull().sum()

Age                        0
Gender                     0
Blood Pressure             0
Cholesterol Level          0
Exercise Habits            0
Smoking                    0
Family Heart Disease       0
Diabetes                   0
BMI                        0
High Blood Pressure        0
Low HDL Cholesterol        0
High LDL Cholesterol       0
Alcohol Consumption     2586
Stress Level               0
Sleep Hours                0
Sugar Consumption          0
Triglyceride Level         0
Fasting Blood Sugar        0
CRP Level                  0
Homocysteine Level         0
Heart Disease Status       0
dtype: int64

In [12]:
print(categorical_cols)

['Gender', 'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level', 'Sugar Consumption', 'Heart Disease Status']

In [13]:
from sklearn.preprocessing import LabelEncoder

# Initialize the encoder
le = LabelEncoder()

# Apply label encoding to all categorical columns
for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))

In [14]:
from sklearn.feature_selection import f_classif

# Perform F-test
f_values, p_values = f_classif(df.drop('Heart Disease Status', axis = 1), df['Heart Disease Status'])


# # Print the name of each feature along with corresponding F-value and p-value
# for feature, f_val, p_val in zip(X.columns, f_values, p_values):
#     print(f"Feature: {feature}\nF-value: {f_val}\nP-value: {p_val}\n")

In [15]:
# Import necessary libraries
from scipy.stats import kurtosis

# Define a function to check if a variable needs exponential smoothing
def needs_smoothing(series, threshold=3):
    # Calculate the kurtosis of the series
    kurt = kurtosis(series)
    # If the kurtosis is greater than the threshold, the series needs smoothing
    return kurt > threshold

# Apply the function to each column in the DataFrame
smoothing_needed = df.apply(needs_smoothing)

# Print the columns that need smoothing
print("Columns that need smoothing:", smoothing_needed[smoothing_needed].index.tolist())

# Apply exponential smoothing to the columns that need it
for col in smoothing_needed[smoothing_needed].index:
    df[col] = np.log1p(df[col])

Columns that need smoothing: []

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import pandas as pd
import joblib

# Separate features and target
X = df.drop('Heart Disease Status', axis=1)
y = df['Heart Disease Status']

# Step 1: Split before SMOTE and scaling
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# Step 2: Apply SMOTE on training data only
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Optional: Feature selection can be done here using X_train_resampled and y_train_resampled

# Step 3: Scale both sets using scaler fitted on training data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# Step 4: Save to files
joblib.dump((X_train_scaled, y_train_resampled), 'X_train_y_train.pkl')
joblib.dump((X_test_scaled, y_test), 'X_test_y_test.pkl')

['X_test_y_test.pkl']

In [17]:
from sklearn.feature_selection import f_classif

# Perform F-test
f_values, p_values = f_classif(X, y)

# Print the name of each feature along with corresponding F-value and p-value
#for feature, f_val, p_val in zip(X.columns, f_values, p_values):
    #print(f"Feature: {feature}\nF-value: {f_val}\nP-value: {p_val}\n")
# Create a DataFrame to hold the feature names, F-values, and p-values
f_test_results = pd.DataFrame({'Feature': X.columns, 'F-value': f_values, 'P-value': p_values})

# Identify the features with F-value less than 1 and reasonable p-value 
drop_features = f_test_results[(f_test_results['F-value'] < 1) & (f_test_results['P-value'] < 0.1)]['Feature']
print(drop_features)
# Drop these features from the DataFrame
X = X.drop(columns=drop_features)


#all vars pass the f-test, tried setting stricter tresholds but worse result on preds

Series([], Name: Feature, dtype: object)

***
# End of preprocessing
***

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize the RandomForestClassifier
rf = RandomForestClassifier(random_state=42)

# Fit the model on the training data
rf.fit(X_train, y_train)

# Predict the target for the test data
y_pred = rf.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy score
print("Accuracy:", accuracy)

# Print the confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Print the classification report
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8
Confusion Matrix:
 [[1600    0]
 [ 400    0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1600
           1       0.00      0.00      0.00       400

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000

/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [19]:
print(y_pred.mean()) #average prediction

0.0

In [20]:
#With PCA:
from sklearn.decomposition import PCA

# Apply PCA to the training data
pca = PCA(n_components=12)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# Initialize the RandomForestClassifier
rf_pca = RandomForestClassifier(random_state=42)

# Fit the model on the training data
rf_pca.fit(X_train_pca, y_train)

# Predict the target for the test data
y_pred_pca = rf_pca.predict(X_test_pca)

# Calculate the accuracy score
accuracy_pca = accuracy_score(y_test, y_pred_pca)

# Print the accuracy score
print("Accuracy with PCA:", accuracy_pca)

# Print the confusion matrix
print("Confusion Matrix with PCA:\n", confusion_matrix(y_test, y_pred_pca))

# Print the classification report
print("Classification Report with PCA:\n", classification_report(y_test, y_pred_pca))

#could  try with some different pca values but coulnt find any that really worked

Accuracy with PCA: 0.8
Confusion Matrix with PCA:
 [[1600    0]
 [ 400    0]]
Classification Report with PCA:
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1600
           1       0.00      0.00      0.00       400

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000

/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))